In [1]:
# library imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sklearn

In [2]:
kaggle = pd.read_csv('data/train.csv')

In [3]:
print(kaggle.shape,'\n')

for col in kaggle.columns:
    print(col)

(192, 24)

version
team
continent
is_host
goals_scored_last_4y
goals_received_last_4y
wins_last_4y
losses_last_4y
draws_last_4y
world_cup_titles_before
squad_total_market_value_eur
fifa_rank_pre_tournament
fifa_points_pre_tournament
squad_avg_age
world_cup_participations_before
groups_passed_before
round16_before
quarterfinals_before
semifinals_before
finals_before
winner
finalist
semi_finalist
quarter_finalist

In [4]:
kaggle.iloc[:,0:12].describe()

,version,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,squad_total_market_value_eur,fifa_rank_pre_tournament
count,192.00000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,1.600000e+02,192.000000
mean,2012.00000,0.036458,84.583333,44.572917,26.046875,11.052083,11.802083,0.427083,3.433053e+08,23.541667
std,6.84916,0.187918,23.731776,13.608009,6.912534,4.745612,3.496055,1.085312,3.489032e+08,18.214497
min,2002.00000,0.000000,28.000000,19.000000,8.000000,2.000000,4.000000,0.000000,6.270000e+06,1.000000
25%,2006.00000,0.000000,66.000000,35.000000,21.000000,8.000000,10.000000,0.000000,9.385750e+07,9.000000
50%,2012.00000,0.000000,83.500000,42.500000,25.000000,10.500000,12.000000,0.000000,2.179400e+08,20.000000
75%,2018.00000,0.000000,102.000000,53.250000,31.000000,14.000000,14.000000,0.000000,4.129750e+08,34.000000
max,2022.00000,1.000000,156.000000,95.000000,48.000000,30.000000,23.000000,5.000000,1.620000e+09,105.000000

In [5]:
kaggle.iloc[:,12:].describe()

,fifa_points_pre_tournament,squad_avg_age,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
count,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000
mean,954.165469,27.249635,5.625000,3.572917,2.244792,2.223958,1.348958,0.697917,0.031250,0.062500,0.125000,0.250000
std,367.544609,1.092351,5.548926,4.584848,2.701071,3.525056,2.618520,1.731263,0.174448,0.242694,0.331584,0.434145
min,285.000000,23.920000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,670.500000,26.560000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,824.000000,27.225000,4.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1182.500000,28.000000,10.000000,6.250000,4.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.250000
max,1841.300000,29.780000,21.000000,19.000000,11.000000,16.000000,13.000000,8.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
kaggle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   version                          192 non-null    int64
 1   team                             192 non-null    object
 2   continent                        192 non-null    object
 3   is_host                          192 non-null    int64
 4   goals_scored_last_4y             192 non-null    int64
 5   goals_received_last_4y           192 non-null    int64
 6   wins_last_4y                     192 non-null    int64
 7   losses_last_4y                   192 non-null    int64
 8   draws_last_4y                    192 non-null    int64
 9   world_cup_titles_before          192 non-null    int64
 10  squad_total_market_value_eur     160 non-null    float64
 11  fifa_rank_pre_tournament         192 non-null    int64
 12  fifa_points_pre_tournament       192 non-null    float64
 13  squad_avg_age                    192 non-null    float64
 14  world_cup_participations_before  192 non-null    int64
 15  groups_passed_before             192 non-null    int64
 16  round16_before                   192 non-null    int64
 17  quarterfinals_before             192 non-null    int64
 18  semifinals_before                192 non-null    int64
 19  finals_before                    192 non-null    int64
 20  winner                           192 non-null    int64
 21  finalist                         192 non-null    int64
 22  semi_finalist                    192 non-null    int64
 23  quarter_finalist                 192 non-null    int64
dtypes: float64(3), int64(19), object(2)
memory usage: 36.1+ KB

In [7]:
folder = 'data/data-csv/'

for file in os.listdir(folder):
    if file.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder, file))
        print(f"\n{file}")
        print(df.shape)
        print(df.columns.tolist())

groups.csv
(159, 7)
['key_id', 'tournament_id', 'tournament_name', 'stage_number', 'stage_name', 'group_name', 'count_teams']

managers.csv
(475, 7)
['key_id', 'manager_id', 'family_name', 'given_name', 'female', 'country_name', 'manager_wikipedia_link']

qualified_teams.csv
(625, 8)
['key_id', 'tournament_id', 'tournament_name', 'team_id', 'team_name', 'team_code', 'count_matches', 'performance']

teams.csv
(88, 14)
['key_id', 'team_id', 'team_name', 'team_code', 'mens_team', 'womens_team', 'federation_name', 'region_name', 'confederation_id', 'confederation_name', 'confederation_code', 'mens_team_wikipedia_link', 'womens_team_wikipedia_link', 'federation_wikipedia_link']

player_appearances.csv
(27432, 21)
['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'position_name', 'position_code', 'starter', 'substitute']

referees.csv
(493, 10)
['key_id', 'referee_id', 'family_name', 'given_name', 'female', 'country_name', 'confederation_id', 'confederation_name', 'confederation_code', 'referee_wikipedia_link']

referee_appearances.csv
(1248, 15)
['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'referee_id', 'family_name', 'given_name', 'country_name', 'confederation_id', 'confederation_name', 'confederation_code']

award_winners.csv
(200, 12)
['key_id', 'tournament_id', 'tournament_name', 'award_id', 'award_name', 'shared', 'player_id', 'family_name', 'given_name', 'team_id', 'team_name', 'team_code']

matches.csv
(1248, 37)
['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'stage_name', 'group_name', 'group_stage', 'knockout_stage', 'replayed', 'replay', 'match_date', 'match_time', 'stadium_id', 'stadium_name', 'city_name', 'country_name', 'home_team_id', 'home_team_name', 'home_team_code', 'away_team_id', 'away_team_name', 'away_team_code', 'score', 'home_team_score', 'away_team_score', 'home_team_score_margin', 'away_team_score_margin', 'extra_time', 'penalty_shootout', 'score_penalties', 'home_team_score_penalties', 'away_team_score_penalties', 'result', 'home_team_win', 'away_team_win', 'draw']

tournaments.csv
(30, 18)
['key_id', 'tournament_id', 'tournament_name', 'year', 'start_date', 'end_date', 'host_country', 'winner', 'host_won', 'count_teams', 'group_stage', 'second_group_stage', 'final_round', 'round_of_16', 'quarter_finals', 'semi_finals', 'third_place_match', 'final']

tournament_standings.csv
(120, 7)
['key_id', 'tournament_id', 'tournament_name', 'position', 'team_id', 'team_name', 'team_code']

substitutions.csv
(10222, 24)
['key_id', 'substitution_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'going_off', 'coming_on']

bookings.csv
(3178, 26)
['key_id', 'booking_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'yellow_card', 'red_card', 'second_yellow_card', 'sending_off']

manager_appearances.csv
(2538, 17)
['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'manager_id', 'family_name', 'given_name', 'country_name']

players.csv
(10401, 13)
['key_id', 'player_id', 'family_name', 'given_name', 'birth_date', 'female', 'goal_keeper', 'defender', 'midfielder', 'forward', 'count_tournaments', 'list_tournaments', 'player_wikipedia_link']

tournament_stages.csv
(155, 16)
['key_id', 'tournament_id', 'tournament_name', 'stage_number', 'stage_name', 'group_stage', 'knockout_stage', 'unbalanced_groups', 'start_date', 'end_date', 'count_matches', 'count_teams', 'count_scheduled', 'count_replays', 'count_playoffs', 'count_walkovers']

confederations.csv
(6, 5)
['key_id', 'confederation_id', 'confederation_name', 'confederation_code', 'confederation_wikipedia_link']

squads.csv
(13843, 12)
['key_id', 'tournament_id', 'tournament_name', 'team_id', 'team_name', 'team_code', 'player_id', 'family_name', 'given_name', 'shirt_number', 'position_name', 'position_code']

group_standings.csv
(626, 19)
['key_id', 'tournament_id', 'tournament_name', 'stage_number', 'stage_name', 'group_name', 'position', 'team_id', 'team_name', 'team_code', 'played', 'wins', 'draws', 'losses', 'goals_for', 'goals_against', 'goal_difference', 'points', 'advanced']

stadiums.csv
(240, 8)
['key_id', 'stadium_id', 'stadium_name', 'city_name', 'country_name', 'stadium_capacity', 'stadium_wikipedia_link', 'city_wikipedia_link']

host_countries.csv
(31, 7)
['key_id', 'tournament_id', 'tournament_name', 'team_id', 'team_name', 'team_code', 'performance']

manager_appointments.csv
(637, 10)
['key_id', 'tournament_id', 'tournament_name', 'team_id', 'team_name', 'team_code', 'manager_id', 'family_name', 'given_name', 'country_name']

referee_appointments.csv
(668, 10)
['key_id', 'tournament_id', 'tournament_name', 'referee_id', 'family_name', 'given_name', 'country_name', 'confederation_id', 'confederation_name', 'confederation_code']

goals.csv
(3637, 27)
['key_id', 'goal_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'player_team_id', 'player_team_name', 'player_team_code', 'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period', 'own_goal', 'penalty']

penalty_kicks.csv
(396, 19)
['key_id', 'penalty_kick_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'match_date', 'stage_name', 'group_name', 'team_id', 'team_name', 'team_code', 'home_team', 'away_team', 'player_id', 'family_name', 'given_name', 'shirt_number', 'converted']

awards.csv
(8, 5)
['key_id', 'award_id', 'award_name', 'award_description', 'year_introduced']

team_appearances.csv
(2496, 36)
['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name', 'stage_name', 'group_name', 'group_stage', 'knockout_stage', 'replayed', 'replay', 'match_date', 'match_time', 'stadium_id', 'stadium_name', 'city_name', 'country_name', 'team_id', 'team_name', 'team_code', 'opponent_id', 'opponent_name', 'opponent_code', 'home_team', 'away_team', 'goals_for', 'goals_against', 'goal_differential', 'extra_time', 'penalty_shootout', 'penalties_for', 'penalties_against', 'result', 'win', 'lose', 'draw']

In [ ]:
# load jfjelstul tables that are most useful
matches = pd.read_csv('data/data-csv/matches.csv')
squads = pd.read_csv('data/data-csv/squads.csv')
players = pd.read_csv('data/data-csv/players.csv')
player_appearances = pd.read_csv('data/data-csv/player_appearances.csv')
goals = pd.read_csv('data/data-csv/goals.csv')
bookings = pd.read_csv('data/data-csv/bookings.csv')
subs = pd.read_csv('data/data-csv/substitutions.csv')

In [9]:
matches.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name',
       'stage_name', 'group_name', 'group_stage', 'knockout_stage', 'replayed',
       'replay', 'match_date', 'match_time', 'stadium_id', 'stadium_name',
       'city_name', 'country_name', 'home_team_id', 'home_team_name',
       'home_team_code', 'away_team_id', 'away_team_name', 'away_team_code',
       'score', 'home_team_score', 'away_team_score', 'home_team_score_margin',
       'away_team_score_margin', 'extra_time', 'penalty_shootout',
       'score_penalties', 'home_team_score_penalties',
       'away_team_score_penalties', 'result', 'home_team_win', 'away_team_win',
       'draw'],
      dtype='object')

In [73]:
# trim tables to 2002 onwards and most useful features
matches_clean = matches[matches['match_date'] > '2000-01-01'][[
        # identifiers
        'tournament_id',
        'match_id',
        'stage_name',
        'group_name',
        'group_stage',
        'knockout_stage',
        'match_date',

        # team info
        'home_team_id',
        'home_team_code',
        'away_team_id',
        'away_team_code',

        # scores and results
        'home_team_score',
        'away_team_score',
        'home_team_win',
        'away_team_win',
        'draw',
        'penalty_shootout'
]].copy()

In [74]:
matches_clean.head()

,tournament_id,match_id,stage_name,group_name,group_stage,knockout_stage,match_date,home_team_id,home_team_code,away_team_id,away_team_code,home_team_score,away_team_score,home_team_win,away_team_win,draw,penalty_shootout
664,WC-2002,M-2002-01,group stage,Group A,1,0,2002-05-31,T-30,FRA,T-65,SEN,0,1,0,1,0,0
665,WC-2002,M-2002-02,group stage,Group E,1,0,2002-06-01,T-60,IRL,T-11,CMR,1,1,0,0,1,0
666,WC-2002,M-2002-03,group stage,Group A,1,0,2002-06-01,T-84,URY,T-22,DNK,1,2,0,1,0,0
667,WC-2002,M-2002-04,group stage,Group E,1,0,2002-06-01,T-31,DEU,T-63,SAU,8,0,1,0,0,0
668,WC-2002,M-2002-05,group stage,Group F,1,0,2002-06-02,T-03,ARG,T-50,NGA,1,0,1,0,0,0

In [30]:
squads.shape

(13843, 12)

In [31]:
squads.tail(10)

,key_id,tournament_id,tournament_name,team_id,team_name,team_code,player_id,family_name,given_name,shirt_number,position_name,position_code
13833,13834,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-34567,Lockyer,Tom,17,defender,DF
13834,13835,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-56664,Williams,Jonny,18,midfielder,MF
13835,13836,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-37173,Harris,Mark,19,forward,FW
13836,13837,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-74707,James,Daniel,20,forward,FW
13837,13838,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-92482,Davies,Adam,21,goal keeper,GK
13838,13839,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-20564,Thomas,Sorba,22,midfielder,MF
13839,13840,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-24982,Levitt,Dylan,23,midfielder,MF
13840,13841,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-02030,Cabango,Ben,24,defender,DF
13841,13842,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-07137,Colwill,Rubin,25,midfielder,MF
13842,13843,WC-2022,2022 FIFA Men's World Cup,T-85,Wales,WAL,P-84269,Smith,Matthew,26,midfielder,MF

In [29]:
squads.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'team_id', 'team_name',
       'team_code', 'player_id', 'family_name', 'given_name', 'shirt_number',
       'position_name', 'position_code'],
      dtype='object')

In [40]:
recent_cups = [f"WC-{4 * x + 2002}" for x in range(6)]
print(recent_cups)

['WC-2002', 'WC-2006', 'WC-2010', 'WC-2014', 'WC-2018', 'WC-2022']

In [71]:
squads_clean = squads[squads['tournament_id'].isin(recent_cups)][[
    'tournament_id',
    'team_code',
    'player_id',
    'family_name',
    'given_name',
    'position_code'
]].copy()

In [72]:
squads_clean.head()

     tournament_id team_code player_id family_name  given_name position_code
7238       WC-2002       ARG   P-56385      Burgos      Germán            GK
7239       WC-2002       ARG   P-83403       Ayala     Roberto            DF
7240       WC-2002       ARG   P-60914       Sorín  Juan Pablo            DF
7241       WC-2002       ARG   P-31684  Pochettino    Mauricio            DF
7242       WC-2002       ARG   P-88203     Almeyda      Matías            MF

In [59]:
players.shape

(10401, 13)

In [60]:
players.head()

,key_id,player_id,family_name,given_name,birth_date,female,goal_keeper,defender,midfielder,forward,count_tournaments,list_tournaments,player_wikipedia_link
0,1,P-35894,A'Court,Alan,1934-09-30,0,0,0,0,1,1,1958,https://en.wikipedia.org/wiki/Alan_A%27Court
1,2,P-29915,Aarønes,Ann Kristin,1973-01-19,1,0,0,1,1,2,"1995, 1999",https://en.wikipedia.org/wiki/Ann_Kristin_Aar%...
2,3,P-03484,Aaronson,Brenden,2000-10-22,0,0,0,0,1,1,2022,https://en.wikipedia.org/wiki/Brenden_Aaronson
3,4,P-04189,Abadzhiev,Stefan,1934-07-03,0,0,0,0,1,1,1966,https://en.wikipedia.org/wiki/Stefan_Abadzhiev
4,5,P-03523,Abalo,Jean-Paul,1975-06-26,0,0,1,0,0,1,2006,https://en.wikipedia.org/wiki/Jean-Paul_Abalo

In [64]:
players.columns

Index(['key_id', 'player_id', 'family_name', 'given_name', 'birth_date',
       'female', 'goal_keeper', 'defender', 'midfielder', 'forward',
       'count_tournaments', 'list_tournaments', 'player_wikipedia_link'],
      dtype='object')

In [69]:
players_clean = players[players['female'] == 0][[
    'player_id',
    'birth_date',
]]

In [70]:
players_clean.head()

  player_id  birth_date
0   P-35894  1934-09-30
2   P-03484  2000-10-22
3   P-04189  1934-07-03
4   P-03523  1975-06-26
6   P-35138  1978-08-03

In [68]:
player_appearances.columns

Index(['key_id', 'tournament_id', 'tournament_name', 'match_id', 'match_name',
       'match_date', 'stage_name', 'group_name', 'team_id', 'team_name',
       'team_code', 'home_team', 'away_team', 'player_id', 'family_name',
       'given_name', 'shirt_number', 'position_name', 'position_code',
       'starter', 'substitute'],
      dtype='object')

In [100]:
player_appearances_clean = player_appearances[player_appearances['match_date'] > '2000-01-01'][[
    'tournament_id',
    'match_id',
    'player_id',
    'starter',
    'substitute'
]]

In [101]:
player_appearances_clean.head(20)

      tournament_id   match_id player_id  starter  substitute
11110       WC-2002  M-2002-01   P-56735        1           0
11111       WC-2002  M-2002-01   P-96540        1           0
11112       WC-2002  M-2002-01   P-80680        1           0
11113       WC-2002  M-2002-01   P-79380        1           0
11114       WC-2002  M-2002-01   P-00916        1           0
11115       WC-2002  M-2002-01   P-51395        1           0
11116       WC-2002  M-2002-01   P-56947        1           0
11117       WC-2002  M-2002-01   P-55991        1           0
11118       WC-2002  M-2002-01   P-40400        1           0
11119       WC-2002  M-2002-01   P-19907        1           0
11120       WC-2002  M-2002-01   P-12167        1           0
11121       WC-2002  M-2002-01   P-53533        0           1
11122       WC-2002  M-2002-01   P-74065        0           1
11123       WC-2002  M-2002-01   P-16571        1           0
11124       WC-2002  M-2002-01   P-27229        1           0
11125       WC-2002  M-2002-01   P-50303        1           0
11126       WC-2002  M-2002-01   P-95302        1           0
11127       WC-2002  M-2002-01   P-62977        1           0
11128       WC-2002  M-2002-01   P-84943        1           0
11129       WC-2002  M-2002-01   P-16046        1           0

In [84]:
goals.columns

Index(['key_id', 'goal_id', 'tournament_id', 'tournament_name', 'match_id',
       'match_name', 'match_date', 'stage_name', 'group_name', 'team_id',
       'team_name', 'team_code', 'home_team', 'away_team', 'player_id',
       'family_name', 'given_name', 'shirt_number', 'player_team_id',
       'player_team_name', 'player_team_code', 'minute_label',
       'minute_regulation', 'minute_stoppage', 'match_period', 'own_goal',
       'penalty'],
      dtype='object')

In [98]:
goals_clean = goals[goals['match_date'] > '2000-01-01'][[
    'goal_id',
    'tournament_id',
    'match_id',
    'player_id',
    'minute_regulation',
    'minute_stoppage',
    'match_period',
    'own_goal',
    'penalty'
]].copy()

In [99]:
goals_clean.head()

,goal_id,tournament_id,match_id,player_id,minute_regulation,minute_stoppage,match_period,own_goal,penalty
2076,G-2077,WC-2002,M-2002-01,P-82212,30,0,first half,0,0
2077,G-2078,WC-2002,M-2002-02,P-18804,39,0,first half,0,0
2078,G-2079,WC-2002,M-2002-02,P-00105,52,0,second half,0,0
2079,G-2080,WC-2002,M-2002-03,P-50534,45,0,first half,0,0
2080,G-2081,WC-2002,M-2002-03,P-49428,47,0,second half,0,0

In [104]:
bookings.columns

Index(['key_id', 'booking_id', 'tournament_id', 'tournament_name', 'match_id',
       'match_name', 'match_date', 'stage_name', 'group_name', 'team_id',
       'team_name', 'team_code', 'home_team', 'away_team', 'player_id',
       'family_name', 'given_name', 'shirt_number', 'minute_label',
       'minute_regulation', 'minute_stoppage', 'match_period', 'yellow_card',
       'red_card', 'second_yellow_card', 'sending_off'],
      dtype='object')

In [105]:
bookings_clean = bookings[bookings['match_date'] > '2000-01-01'][[
    'booking_id',
    'tournament_id',
    'match_id',
    'team_code',
    'home_team',
    'away_team',
    'player_id',
    'minute_regulation',
    'minute_stoppage',
    'match_period',
    'yellow_card',
    'red_card',
    'second_yellow_card',
    'sending_off'
]]

In [107]:
bookings_clean.head()

,booking_id,tournament_id,match_id,team_code,home_team,away_team,player_id,minute_regulation,minute_stoppage,match_period,yellow_card,red_card,second_yellow_card,sending_off
1216,B-1217,WC-2002,M-2002-01,FRA,1,0,P-40400,45,2,"first half, stoppage time",1,0,0,0
1217,B-1218,WC-2002,M-2002-01,SEN,0,1,P-95302,51,0,second half,1,0,0,0
1218,B-1219,WC-2002,M-2002-02,IRL,1,0,P-15705,30,0,first half,1,0,0,0
1219,B-1220,WC-2002,M-2002-02,IRL,1,0,P-56778,51,0,second half,1,0,0,0
1220,B-1221,WC-2002,M-2002-02,IRL,1,0,P-19727,82,0,second half,1,0,0,0

In [108]:
subs.columns

Index(['key_id', 'substitution_id', 'tournament_id', 'tournament_name',
       'match_id', 'match_name', 'match_date', 'stage_name', 'group_name',
       'team_id', 'team_name', 'team_code', 'home_team', 'away_team',
       'player_id', 'family_name', 'given_name', 'shirt_number',
       'minute_label', 'minute_regulation', 'minute_stoppage', 'match_period',
       'going_off', 'coming_on'],
      dtype='object')

In [109]:
subs_clean = subs[subs['match_date'] > '2000-01-01'][[
    'substitution_id',
    'tournament_id',
    'match_id',
    'team_code',
    'home_team',
    'away_team',
    'player_id',
    'minute_regulation',
    'minute_stoppage',
    'match_period',
    'going_off',
    'coming_on'
]]

In [110]:
subs_clean.head()

,substitution_id,tournament_id,match_id,team_code,home_team,away_team,player_id,minute_regulation,minute_stoppage,match_period,going_off,coming_on
3230,S-3231,WC-2002,M-2002-01,FRA,1,0,P-80680,60,0,second half,1,0
3231,S-3232,WC-2002,M-2002-01,FRA,1,0,P-74065,60,0,second half,0,1
3232,S-3233,WC-2002,M-2002-01,FRA,1,0,P-00916,81,0,second half,1,0
3233,S-3234,WC-2002,M-2002-01,FRA,1,0,P-53533,81,0,second half,0,1
3234,S-3235,WC-2002,M-2002-02,IRL,1,0,P-15705,46,0,second half,1,0